[project]
site_name = "NAISS Intro to Python"
site_url = "https://uppmax.github.io/naiss_intro_python/"
repo_url = "https://github.com/UPPMAX/naiss_intro_python"

nav = [
  { "Start" = "index.md"},
  {"Learning outcomes" = "learning_outcomes.md"},
  {"Prerequisites" = "prereqs/README.md"},
  {"Course dates" = "course_dates.md"},
  {"Schedule" = "schedule.md"},
  {"Getting it to run" = [
     "sessions/introduction_getting_it_to_run.md",
     "sessions/using_the_python_interpreter.md",
     "sessions/the_way_of_the_program.md",
     "sessions/working_with_python_scripts.md"
  ]}
]


[project.extra.analytics]
provider = "google"
property = "G-CW0S3VK5Z0"

#     nav:
#       - Getting it to run:
#     #     - Overview: sessions/introduction_getting_it_to_run.md
#     #     - Using The Python interpreter: sessions/using_the_python_interpreter.md
#     #     - The Way Of The Program: sessions/the_way_of_the_program.md
#     #     - Working with Python scripts: sessions/working_with_python_scripts.md
#       - Basic Python:
#     #     - Overview: sessions/introduction_basic_python.md
#     #     - Variables, expressions and statements, variables: sessions/variables_expressions_and_statements_1.md
#     #     - Variables, expressions and statements, operators: sessions/variables_expressions_and_statements_2.md
#     #     - Variables, expressions and statements, user input: sessions/variables_expressions_and_statements_3.md
#     #     # - Modules and Python packages: sessions/hello_little_turtles.md
#     #     - File IO: sessions/files.md
#     #     - Command-line arguments: sessions/command_line_arguments.md
#     #     # -  Graphics: sessions/graphics.md
#     #     - Functions: sessions/functions.md
#     #     - Further learning: further_learning.md
#     #     - Summary: summary.md
#       - Misc:
#     #     - Acknowledgements: acknowledgements.md
#     #     - All topics: topics.md
#     #     - Code of conduct: CODE_OF_CONDUCT.md
#     #     - Contributing: CONTRIBUTING.md
#     #     - Communication: communication/README.md
#     #     - Data: data/README.md
#     #     - Deploy locally: deploy_locally.md
#     #     - Evaluation: evaluation.md
#     #     - Evaluations:  evaluations/README.md
#     #     - Exercise procedure: misc/exercise_procedure.md
#     #     - Frequently asked questions: faq.md
#     #     - Lesson plans: lesson_plans/README.md
#     #     - Project: misc/project.md
#     #     - Reflections: reflections/README.md
#       - Contact us: contact_us.md
